"""add indexes

Revision ID: 1022437f20e7
Revises: d4e5f6a7b8c9
Create Date: 2026-09-20 14:46:35.349904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1022437f20e7'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_asset_assignments_assigned_by'), 'asset_assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_asset_assignments_employee_id'), 'asset_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_asset_components_asset_id'), 'asset_components', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_returns_received_by_user_id'), 'asset_returns', ['received_by_user_id'], unique=False)
    op.create_index(op.f('ix_asset_returns_returned_by_employee_id'), 'asset_returns', ['returned_by_employee_id'], unique=False)
    op.create_index(op.f('ix_asset_transfers_approved_by'), 'asset_transfers', ['approved_by'], unique=False)
    op.create_index(op.f('ix_asset_transfers_asset_id'), 'asset_transfers', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_transfers_from_employee_id'), 'asset_transfers', ['from_employee_id'], unique=False)
    op.create_index(op.f('ix_asset_transfers_requested_by'), 'asset_transfers', ['requested_by'], unique=False)
    op.create_index(op.f('ix_asset_transfers_to_employee_id'), 'asset_transfers', ['to_employee_id'], unique=False)
    op.create_index(op.f('ix_assets_asset_type_id'), 'assets', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_assets_location_id'), 'assets', ['location_id'], unique=False)
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index(op.f('ix_assets_vendor_id'), 'assets', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_assignment_items_asset_id'), 'assignment_items', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assignment_items_status'), 'assignment_items', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_device_agents_asset_id'), 'device_agents', ['asset_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by'), 'documents', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_employees_department_id'), 'employees', ['department_id'], unique=False)
    op.create_index(op.f('ix_employees_employment_status'), 'employees', ['employment_status'], unique=False)
    op.create_index(op.f('ix_employees_group_id'), 'employees', ['group_id'], unique=False)
    op.create_index(op.f('ix_employees_location_id'), 'employees', ['location_id'], unique=False)
    op.create_index(op.f('ix_employees_manager_id'), 'employees', ['manager_id'], unique=False)
    op.drop_constraint('issued_tokens_jti_key', 'issued_tokens', type_='unique')
    op.create_index(op.f('ix_issued_tokens_jti'), 'issued_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_organization_settings_updated_by'), 'organization_settings', ['updated_by'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_repair_history_changed_by'), 'repair_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_repair_history_repair_ticket_id'), 'repair_history', ['repair_ticket_id'], unique=False)
    op.create_index(op.f('ix_repair_tickets_asset_id'), 'repair_tickets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_repair_tickets_reported_by'), 'repair_tickets', ['reported_by'], unique=False)
    op.create_index(op.f('ix_repair_tickets_status'), 'repair_tickets', ['status'], unique=False)
    op.create_index(op.f('ix_repair_tickets_vendor_id'), 'repair_tickets', ['vendor_id'], unique=False)
    op.drop_constraint('revoked_tokens_jti_key', 'revoked_tokens', type_='unique')
    op.drop_index('ix_revoked_tokens_jti', table_name='revoked_tokens')
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_software_assignments_employee_id'), 'software_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_software_assignments_license_id'), 'software_assignments', ['license_id'], unique=False)
    op.create_index(op.f('ix_software_licenses_software_id'), 'software_licenses', ['software_id'], unique=False)
    op.create_index(op.f('ix_software_licenses_vendor_id'), 'software_licenses', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_warranties_asset_id'), 'warranties', ['asset_id'], unique=False)
    op.create_index(op.f('ix_warranties_vendor_id'), 'warranties', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warranties_vendor_id'), table_name='warranties')
    op.drop_index(op.f('ix_warranties_asset_id'), table_name='warranties')
    op.drop_index(op.f('ix_software_licenses_vendor_id'), table_name='software_licenses')
    op.drop_index(op.f('ix_software_licenses_software_id'), table_name='software_licenses')
    op.drop_index(op.f('ix_software_assignments_license_id'), table_name='software_assignments')
    op.drop_index(op.f('ix_software_assignments_employee_id'), table_name='software_assignments')
    op.drop_index(op.f('ix_revoked_tokens_user_id'), table_name='revoked_tokens')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.create_index('ix_revoked_tokens_jti', 'revoked_tokens', ['jti'], unique=False)
    op.create_unique_constraint('revoked_tokens_jti_key', 'revoked_tokens', ['jti'])
    op.drop_index(op.f('ix_repair_tickets_vendor_id'), table_name='repair_tickets')
    op.drop_index(op.f('ix_repair_tickets_status'), table_name='repair_tickets')
    op.drop_index(op.f('ix_repair_tickets_reported_by'), table_name='repair_tickets')
    op.drop_index(op.f('ix_repair_tickets_asset_id'), table_name='repair_tickets')
    op.drop_index(op.f('ix_repair_history_repair_ticket_id'), table_name='repair_history')
    op.drop_index(op.f('ix_repair_history_changed_by'), table_name='repair_history')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_organization_settings_updated_by'), table_name='organization_settings')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_issued_tokens_jti'), table_name='issued_tokens')
    op.create_unique_constraint('issued_tokens_jti_key', 'issued_tokens', ['jti'])
    op.drop_index(op.f('ix_employees_manager_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_location_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_group_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employment_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_department_id'), table_name='employees')
    op.drop_index(op.f('ix_documents_uploaded_by'), table_name='documents')
    op.drop_index(op.f('ix_device_agents_asset_id'), table_name='device_agents')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_assignment_items_status'), table_name='assignment_items')
    op.drop_index(op.f('ix_assignment_items_asset_id'), table_name='assignment_items')
    op.drop_index(op.f('ix_assets_vendor_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_index(op.f('ix_assets_location_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type_id'), table_name='assets')
    op.drop_index(op.f('ix_asset_transfers_to_employee_id'), table_name='asset_transfers')
    op.drop_index(op.f('ix_asset_transfers_requested_by'), table_name='asset_transfers')
    op.drop_index(op.f('ix_asset_transfers_from_employee_id'), table_name='asset_transfers')
    op.drop_index(op.f('ix_asset_transfers_asset_id'), table_name='asset_transfers')
    op.drop_index(op.f('ix_asset_transfers_approved_by'), table_name='asset_transfers')
    op.drop_index(op.f('ix_asset_returns_returned_by_employee_id'), table_name='asset_returns')
    op.drop_index(op.f('ix_asset_returns_received_by_user_id'), table_name='asset_returns')
    op.drop_index(op.f('ix_asset_components_asset_id'), table_name='asset_components')
    op.drop_index(op.f('ix_asset_assignments_employee_id'), table_name='asset_assignments')
    op.drop_index(op.f('ix_asset_assignments_assigned_by'), table_name='asset_assignments')
    # ### end Alembic commands ###
