"""phase_b_taxonomy

Revision ID: 46fee0f659ca
Revises: f1g2h3i4j5k6
Create Date: 2026-09-21 07:38:44.844948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fee0f659ca'
down_revision: Union[str, None] = 'f1g2h3i4j5k6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('software_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('asset_types', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_asset_types_category_id'), 'asset_types', ['category_id'], unique=False)
    op.create_foreign_key(None, 'asset_types', 'asset_categories', ['category_id'], ['id'])
    op.create_foreign_key('fk_org_units_manager_id', 'org_units', 'employees', ['manager_id'], ['id'], use_alter=True)
    op.add_column('software', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_software_category_id'), 'software', ['category_id'], unique=False)
    op.create_foreign_key(None, 'software', 'software_categories', ['category_id'], ['id'])
    
    # --- Data Migration: Software Categories ---
    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT id, category FROM software WHERE category IS NOT NULL AND category != ''"))
    
    categories_map = {}
    for row in result:
        software_id = row[0]
        cat_name = row[1]
        
        if cat_name not in categories_map:
            cat_res = bind.execute(sa.text("SELECT id FROM software_categories WHERE name = :name"), {"name": cat_name}).fetchone()
            if cat_res:
                categories_map[cat_name] = cat_res[0]
            else:
                res = bind.execute(sa.text("INSERT INTO software_categories (name, status) VALUES (:name, 'ACTIVE') RETURNING id"), {"name": cat_name})
                categories_map[cat_name] = res.fetchone()[0]
                
        cat_id = categories_map[cat_name]
        bind.execute(sa.text("UPDATE software SET category_id = :cat_id WHERE id = :id"), {"cat_id": cat_id, "id": software_id})
    # -------------------------------------------

    op.drop_column('software', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('software', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'software', type_='foreignkey')
    op.drop_index(op.f('ix_software_category_id'), table_name='software')
    op.drop_column('software', 'category_id')
    op.drop_constraint('fk_org_units_manager_id', 'org_units', type_='foreignkey')
    op.drop_constraint(None, 'asset_types', type_='foreignkey')
    op.drop_index(op.f('ix_asset_types_category_id'), table_name='asset_types')
    op.drop_column('asset_types', 'category_id')
    op.drop_table('software_categories')
    op.drop_table('asset_categories')
    # ### end Alembic commands ###
