"""phase_c_lifecycle_fields

Revision ID: 99e174c9cd80
Revises: 46fee0f659ca
Create Date: 2026-09-21 09:09:14.474906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99e174c9cd80'
down_revision: Union[str, None] = '46fee0f659ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_disposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('disposal_date', sa.Date(), nullable=False),
    sa.Column('disposal_method', sa.Enum('SOLD', 'SCRAPPED', 'DONATED', 'RECYCLED', 'RETURNED_TO_LESSOR', name='disposalmethod'), nullable=False),
    sa.Column('disposal_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('authorized_by_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['authorized_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('service_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_contracts_asset_id'), 'service_contracts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_service_contracts_vendor_id'), 'service_contracts', ['vendor_id'], unique=False)
    op.add_column('assets', sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('assets', sa.Column('salvage_value', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('assets', sa.Column('useful_life_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'useful_life_years')
    op.drop_column('assets', 'salvage_value')
    op.drop_column('assets', 'tags')
    op.drop_index(op.f('ix_service_contracts_vendor_id'), table_name='service_contracts')
    op.drop_index(op.f('ix_service_contracts_asset_id'), table_name='service_contracts')
    op.drop_table('service_contracts')
    op.drop_table('asset_disposals')
    # ### end Alembic commands ###
