"""phase_d_license_enhancements

Revision ID: d27464e9dc8d
Revises: 99e174c9cd80
Create Date: 2026-09-21 09:29:54.032605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27464e9dc8d'
down_revision: Union[str, None] = '99e174c9cd80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('software_assignments', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.alter_column('software_assignments', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_software_assignments_asset_id'), 'software_assignments', ['asset_id'], unique=False)
    op.create_foreign_key(None, 'software_assignments', 'assets', ['asset_id'], ['id'])
    op.add_column('software_licenses', sa.Column('purchase_cost', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_check_constraint(
        'chk_assignment_target_mutually_exclusive',
        'software_assignments',
        "(employee_id IS NOT NULL AND asset_id IS NULL) OR (employee_id IS NULL AND asset_id IS NOT NULL)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_assignment_target_mutually_exclusive', 'software_assignments', type_='check')
    op.drop_column('software_licenses', 'purchase_cost')
    op.drop_constraint(None, 'software_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_software_assignments_asset_id'), table_name='software_assignments')
    op.alter_column('software_assignments', 'employee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('software_assignments', 'asset_id')
    # ### end Alembic commands ###
